### ISSUE TITLE
Use private tempstore instead of accessing $_SESSION directly

### ISSUE THREAD

**Issue by WengerK** [gridonic/commerce_google_tag_manager#1]
Thanks @wanze for your amazing works on this !

**Problem/Motivation**
Drupal 8 provides a means to access session variables by utilizing the private tempstore. Directly accessing PHP's $_SESSION should be avoided.

The module is using the `$_SESSION` global at various occasions to temporarily save next events to dispatch.

**Proposed resolution**
Utilize te `tempstore.private` service to access the session variables.

**Remaining tasks**
Patch/PR to create.

**User interface changes**
None.

**API changes**
Adds a dependency in Drupal 8.5+ core to the module.

**Data model changes**
None.

**Comment by wanze** [comment]
@WengerK The referenced commit implements your suggestion. Please let me know what you think if you find time to take a look.

Btw, thanks for the detailed issue description 👍

**Comment by WengerK** [comment]
It's pretty cool thanks for the changes !
